### ISSUE TITLE
Create a page to monitor requests

### ISSUE THREAD

**Issue by belgamo** [comarev/comarev-dashboard#50]
The companies need to have a way to make sure that the customer paid all invoices. We have an endpoint that returns all requests when a QR Code is scanned at the company. We need a page where the managers can see these requests with the confirmation of whether the user is ok or not.

https://github.com/comarev/comarev/pull/54

**Comment by BrunoViveiros** [comment]
@belgamo can I take this one?

**Comment by mse-moises** [comment]
@belgamo Can i take this one?
