### ISSUE TITLE
Add tests for RoleFilter component

### ISSUE THREAD

**Issue by belgamo** [comarev/comarev-dashboard#52]
RoleFilter is a component that receives `children` and an array of roles. We need to check if it returns `null` when the user doesn't have the proper roles.

**Comment by perchespierri** [comment]
I would like to do this one !

**Comment by m-pereira** [comment]
@Isaac-alencar please, ask for assign next time :) @perchespierri I'm sorry for this, and I'm sure you can help us with another issue :)

**Comment by Isaac-alencar** [comment]
@m-pereira, @belgamo and @perchespierri  I'm sorry about it, I will ask to assign next time!
